# Generated by Django 5.1.6 on 2025-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('setor', models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Financeiro', 'Financeiro'), ('Atendimento', 'Atendimento'), ('Orçamento', 'Orçamento'), ('TI', 'TI')], max_length=100)),
            ],
        ),
    ]
